version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/app.dockerfile
    working_dir: /var/www
    restart: always
    volumes:
      - ./:/var/www
  web:
    build:
      context: ./
      dockerfile: ./docker/web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 80:80
    restart: always
  redis:
    image: redis
    ports:
      - 6379:6379
